argument returning undefined when the type is GuildText
discordeno/template pull request #144
Opened 2021-06-23 02:46 UTC by remagnedlogeht

2021-06-23 05:23 UTC, itohatweb approved these changes

2021-06-23 05:24 UTC, itohatweb requested changes

2021-06-23 05:24 UTC, itohatweb commented on src/arguments/guildtextchannel.ts
> +    if (channel?.type !== undefined || !textChannelTypes.includes(channel.type)) {
```suggestion
    if (channel?.type === undefined || !textChannelTypes.includes(channel.type)) {
```

2021-06-25 04:21 UTC, Skillz4Killz approved these changes

2021-06-25 05:22 UTC, itohatweb approved these changes

2021-06-25 05:22 UTC, merged